topictalk/topictalk/post/urls.py
from django.urls import path, include

from topictalk.post import views

urlpatterns = [
    path('create/', views.post_create, name='post-create'),
    path('details/<int:pk>/', views.post_details, name='post-details'),
    path('minecraft/', views.minecraft, name='minecraft'),
    path('league_of_legends/', views.league_of_legends, name='league of legends'),
    path('nba/', views.nba, name='nba'),
    path('premier_league/', views.premier_league, name='premier league'),
    path('bitecoin/', views.bitecoin, name='bitecoin'),
    path('litecoin/', views.litecoin, name='litecoin'),
    path('comment/<int:post_id>/', views.add_comment, name='comment'),
    path('delete/<int:post_id>/', views.delete_post, name='delete-post'),
    path('delete_comment/<int:comment_id>/<int:post_id>/', views.delete_comment, name='delete-comment')
]

topictalk/topictalk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('topictalk.common.urls')),
    path('account/', include('topictalk.account.urls')),
    path('post/', include('topictalk.post.urls')),
]


topictalk/topictalk/post/models.py
from django.db import models

from topictalk.account.models import TopicTalkUser
from topictalk.post.validators import validate_file_size

# Create your models here.
class Post(models.Model):
    Community = (
        ('League of Legends', 'League of Legends'),
        ('Minecraft', 'Minecraft'),
        ('NBA', 'NBA'),
        ('Premier League', 'Premier League'),
        ('Bitecoin', 'Bitecoin'),
        ('Litecoin', 'Litecoin')
    )
    choose_community = models.CharField(max_length=20, choices=Community)
    post_title = models.CharField(max_length=30)
    post_content = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='images', blank=True, null=True, validators=[validate_file_size])
    date_time_of_publication = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(TopicTalkUser, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.post_title

    class Meta:
        ordering = ['-date_time_of_publication']


class Comment(models.Model):
    text = models.TextField(max_length=300)
    date_time_of_publication = models.DateTimeField(auto_now_add=True)
    to_post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date_time_of_publication']


class Like(models.Model):
    to_post = models.ForeignKey(Post, on_delete=models.CASCADE)


class LikeComment(models.Model):
    to_comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

topictalk/topictalk/post/forms.py
from django import forms
from topictalk.post.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['choose_community', 'post_title', 'post_content', 'image']
        widgets = {
            'post_title': forms.TextInput(attrs={'placeholder': 'Post Title', 'class': 'border-widget'}),
            'post_content': forms.Textarea(attrs={"size": 10})
        }
        labels = {
            'post_title': "Post Title",
            'post_content': 'Post Content'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

        widgets = {
            'text': forms.Textarea(attrs={'id': 'comment'})
        }

        labels = {
            'text': 'Your Comment:'
        }

topictalk/topictalk/post/views.py
from django.shortcuts import render, redirect

from topictalk.common.forms import SearchForm
from topictalk.post.forms import PostForm, CommentForm
from topictalk.post.models import Post, Like, Comment, LikeComment


# Create your views here.


def post_details(request, pk):
    current_post = Post.objects.get(pk=pk)
    comments = current_post.comment_set.all()
    comment_form = CommentForm()

    context = {
        'current_post': current_post,
        'comments': comments,
        'comment_form': comment_form,
    }

    return render(request, template_name='post/post-details.html', context=context)


def minecraft(request):
    minecraft_posts = Post.objects.filter(choose_community='Minecraft')
    search_form = SearchForm()

    if request.method == "POST":
        search_form = SearchForm(request.POST)
        if search_form.is_valid():
            minecraft_posts = minecraft_posts.filter(
                choose_community__icontains=search_form.cleaned_data['community_name'])

    context = {
        'minecraft_posts': minecraft_posts,
        'search_form': search_form
    }

    return render(request, template_name='post/minecraft-post.html', context=context)


def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        post.save()
        return redirect('home')

    context = {
        'form': form,
    }

    return render(request, template_name='post/post-page.html', context=context)


def add_comment(request, post_id):
    if request.method == 'POST':
        post = Post.objects.get(id=post_id)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.to_post = post
            comment.save()

        return redirect(request.META['HTTP_REFERER'] + f'#{post_id}')


def league_of_legends(request):
    league_of_legends_posts = Post.objects.filter(choose_community='League of Legends')
    search_form = SearchForm()
    context = {
        'league_of_legends_posts': league_of_legends_posts,
        'search_form': search_form
    }

    return render(request, template_name='post/league-of-legends.html', context=context)


def nba(request):
    nba_posts = Post.objects.filter(choose_community='NBA')
    search_form = SearchForm()
    context = {
        'nba_posts': nba_posts,
        'search_form': search_form
    }

    return render(request, template_name='post/NBA.html', context=context)


def premier_league(request):
    premier_league_posts = Post.objects.filter(choose_community='Premier League')
    search_form = SearchForm()
    context = {
        'premier_league_posts': premier_league_posts,
        'search_form': search_form
    }

    return render(request, template_name='post/premier_league.html', context=context)


def bitecoin(request):
    bitecoin_posts = Post.objects.filter(choose_community='Bitecoin')
    search_form = SearchForm()
    context = {
        'bitecoin_posts': bitecoin_posts,
        'search_form': search_form
    }

    return render(request, template_name='post/bitecoin.html', context=context)


def litecoin(request):
    litecoin_posts = Post.objects.filter(choose_community='Litecoin')
    search_form = SearchForm()
    context = {
        'litecoin_posts': litecoin_posts,
        'search_form': search_form
    }

    return render(request, template_name='post/litecoin.html', context=context)


def delete_post(request, post_id):
    current_post = Post.objects.get(pk=post_id)
    current_post.delete()
    return redirect('home')


def delete_comment(request, comment_id, post_id):
    comment = Comment.objects.get(pk=comment_id)
    comment.delete()
    return redirect('post-details', pk=post_id)

topictalk/topictalk/post/templates/post/NBA.html
{% extends 'base.html' %}

{% block content %}
    <!doctype html>
    <html lang="en" data-bs-theme="auto">
    <head>
        <script src="../assets/js/color-modes.js"></script>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Album example · Bootstrap v5.3</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/minecraft.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <link rel="stylesheet" href="/static/css/header.css">


    </head>
    <body>
    <div class="about-community">
        <div class="community-container">
            <h2>About Section</h2>
            <p>Immerse yourself in the NBA world with our featured content!</p>
            <a class="btn btn-outline-primary me-2" href="{% url 'post-create' %}">Create
                post</a>
        </div>
    </div>
    <h1 class="hedaer-minecraft">NBA</h1>
    {% for current_post in nba_posts %}
        <div class="post" onclick="location.href='{% url "post-details" current_post.pk %}'">
            <div class="post-user">
                <img class="user-image" src="https://via.placeholder.com/40" alt="User Image">
                <div>
                    <p class="user-name">{{ current_post.user.username }}</p>
                    <p class="posted-hours">Posted on {{ current_post.date_time_of_publication }}</p>
                </div>
            </div>
            <h2 class="post-title">{{ current_post.post_title }}</h2>
            <p class="post-content">{{ current_post.post_content }}</p>
            <div class="imgBx" id="{{ current_post.id }}">
                {% if current_post.image %}
                    <img class="post-image" src="{{ current_post.image.url }}" alt="Image 1">
                {% endif %}
            </div>
            <div class="post-buttons">
                {% if request.user.is_authenticated %}
                    <a class="button" href="{% url 'like' current_post.id %}"><i class="icon fas fa-thumbs-up"></i>Like<span
                            class="count">{{ current_post.like_set.count }}</span></a>
                    <a class="button" href="{% url 'post-details' current_post.id %}?scroll_to_comment=true"><i
                            class="icon fas fa-comment"></i>Comment<span
                            class="count">{{ current_post.comment_set.count }}</span></a>
                {% else %}
                    <a class="button" href="{% url 'login' %}"><i class="icon fas fa-thumbs-up"></i>Like<span
                            class="count">{{ current_post.like_set.count }}</span></a>
                    <a class="button" href="{% url 'login' %}?scroll_to_comment=true"><i
                            class="icon fas fa-comment"></i>Comment<span
                            class="count">{{ current_post.comment_set.count }}</span></a>
                {% endif %}
            </div>
        </div>
    {% endfor %}

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const categories = document.querySelectorAll('.category');

            categories.forEach(category => {
                category.addEventListener('click', () => {
                    category.classList.toggle('active');
                    updateArrowIcon(category);
                });
            });

            function updateArrowIcon(category) {
                const arrow = category.querySelector('.arrow');
                const subcategories = category.querySelector('.subcategories');

                if (category.classList.contains('active')) {
                    arrow.style.transform = 'rotate(90deg)';
                    subcategories.style.maxHeight = subcategories.scrollHeight + 'px';
                } else {
                    arrow.style.transform = 'rotate(0deg)';
                    subcategories.style.maxHeight = '0';
                }
            }
        });
    </script>
    </body>
    </html>

{% endblock %}

topictalk/topictalk/post/templates/post/bitecoin.html
{% extends 'base.html' %}

{% block content %}
    <!doctype html>
    <html lang="en" data-bs-theme="auto">
    <head>
        <script src="../assets/js/color-modes.js"></script>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Album example · Bootstrap v5.3</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/minecraft.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <link rel="stylesheet" href="/static/css/header.css">


    </head>
    <body>
    <div class="about-community">
        <div class="community-container">
            <h2>About Section</h2>
            <p>Explore the world of Bitcoin and cryptocurrency with our featured content!</p>
            <a class="btn btn-outline-primary me-2" href="{% url 'post-create' %}">Create
                post</a>
        </div>
    </div>
    <h1 class="hedaer-minecraft">Bitecoin</h1>
    {% for current_post in bitecoin_posts %}
        <div class="post" onclick="location.href='{% url "post-details" current_post.pk %}'">
            <div class="post-user">
                <img class="user-image" src="https://via.placeholder.com/40" alt="User Image">
                <div>
                    <p class="user-name">{{ current_post.user.username }}</p>
                    <p class="posted-hours">Posted on {{ current_post.date_time_of_publication }}</p>
                </div>
            </div>
            <h2 class="post-title">{{ current_post.post_title }}</h2>
            <p class="post-content">{{ current_post.post_content }}</p>
            <div class="imgBx" id="{{ current_post.id }}">
                {% if current_post.image %}
                    <img class="post-image" src="{{ current_post.image.url }}" alt="Image 1">
                {% endif %}
            </div>
            <div class="post-buttons">
                {% if request.user.is_authenticated %}
                    <a class="button" href="{% url 'like' current_post.id %}"><i class="icon fas fa-thumbs-up"></i>Like<span
                            class="count">{{ current_post.like_set.count }}</span></a>
                    <a class="button" href="{% url 'post-details' current_post.id %}?scroll_to_comment=true"><i
                            class="icon fas fa-comment"></i>Comment<span
                            class="count">{{ current_post.comment_set.count }}</span></a>
                {% else %}
                    <a class="button" href="{% url 'login' %}"><i class="icon fas fa-thumbs-up"></i>Like<span
                            class="count">{{ current_post.like_set.count }}</span></a>
                    <a class="button" href="{% url 'login' %}?scroll_to_comment=true"><i
                            class="icon fas fa-comment"></i>Comment<span
                            class="count">{{ current_post.comment_set.count }}</span></a>
                {% endif %}
            </div>
        </div>
    {% endfor %}

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const categories = document.querySelectorAll('.category');

            categories.forEach(category => {
                category.addEventListener('click', () => {
                    category.classList.toggle('active');
                    updateArrowIcon(category);
                });
            });

            function updateArrowIcon(category) {
                const arrow = category.querySelector('.arrow');
                const subcategories = category.querySelector('.subcategories');

                if (category.classList.contains('active')) {
                    arrow.style.transform = 'rotate(90deg)';
                    subcategories.style.maxHeight = subcategories.scrollHeight + 'px';
                } else {
                    arrow.style.transform = 'rotate(0deg)';
                    subcategories.style.maxHeight = '0';
                }
            }
        });
    </script>
    </body>
    </html>

{% endblock %}

topictalk/topictalk/post/templates/post/league-of-legends.html
{% extends 'base.html' %}

{% block content %}
    <!doctype html>
    <html lang="en" data-bs-theme="auto">
    <head>
        <script src="../assets/js/color-modes.js"></script>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Album example · Bootstrap v5.3</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/minecraft.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <link rel="stylesheet" href="/static/css/header.css">


    </head>
    <body>
    <div class="about-community">
        <div class="community-container">
            <h2>About Section</h2>
            <p>Dive into the world of League of Legends with our curated content!</p>
            <a class="btn btn-outline-primary me-2" href="{% url 'post-create' %}">Create
                post</a>
        </div>
    </div>
    <h1 class="hedaer-minecraft">League of Legends</h1>
    {% for current_post in league_of_legends_posts %}
        <div class="post" onclick="location.href='{% url "post-details" current_post.pk %}'">
            <div class="post-user">
                <img class="user-image" src="https://via.placeholder.com/40" alt="User Image">
                <div>
                    <p class="user-name">{{ current_post.user.username }}</p>
                    <p class="posted-hours">Posted on {{ current_post.date_time_of_publication }}</p>
                </div>
            </div>
            <h2 class="post-title">{{ current_post.post_title }}</h2>
            <p class="post-content">{{ current_post.post_content }}</p>
            <div class="imgBx" id="{{ current_post.id }}">
                {% if current_post.image %}
                    <img class="post-image" src="{{ current_post.image.url }}" alt="Image 1">
                {% endif %}
            </div>
            <div class="post-buttons">
                {% if request.user.is_authenticated %}
                    <a class="button" href="{% url 'like' current_post.id %}"><i class="icon fas fa-thumbs-up"></i>Like<span
                            class="count">{{ current_post.like_set.count }}</span></a>
                    <a class="button" href="{% url 'post-details' current_post.id %}?scroll_to_comment=true"><i
                            class="icon fas fa-comment"></i>Comment<span
                            class="count">{{ current_post.comment_set.count }}</span></a>
                {% else %}
                    <a class="button" href="{% url 'login' %}"><i class="icon fas fa-thumbs-up"></i>Like<span
                            class="count">{{ current_post.like_set.count }}</span></a>
                    <a class="button" href="{% url 'login' %}?scroll_to_comment=true"><i
                            class="icon fas fa-comment"></i>Comment<span
                            class="count">{{ current_post.comment_set.count }}</span></a>
                {% endif %}
            </div>
        </div>
    {% endfor %}

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const categories = document.querySelectorAll('.category');

            categories.forEach(category => {
                category.addEventListener('click', () => {
                    category.classList.toggle('active');
                    updateArrowIcon(category);
                });
            });

            function updateArrowIcon(category) {
                const arrow = category.querySelector('.arrow');
                const subcategories = category.querySelector('.subcategories');

                if (category.classList.contains('active')) {
                    arrow.style.transform = 'rotate(90deg)';
                    subcategories.style.maxHeight = subcategories.scrollHeight + 'px';
                } else {
                    arrow.style.transform = 'rotate(0deg)';
                    subcategories.style.maxHeight = '0';
                }
            }
        });
    </script>
    </body>
    </html>

{% endblock %}

topictalk/topictalk/post/templates/post/litecoin.html
{% extends 'base.html' %}

{% block content %}
    <!doctype html>
    <html lang="en" data-bs-theme="auto">
    <head>
        <script src="../assets/js/color-modes.js"></script>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Album example · Bootstrap v5.3</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/minecraft.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <link rel="stylesheet" href="/static/css/header.css">


    </head>
    <body>
    <div class="about-community">
        <div class="community-container">
            <h2>About Section</h2>
            <p>Dive into the world of Litecoin and cryptocurrency with our featured content!</p>
            <a class="btn btn-outline-primary me-2" href="{% url 'post-create' %}">Create
                post</a>
        </div>
    </div>
    <h1 class="hedaer-minecraft">Litecoin</h1>
    {% for current_post in litecoin_posts %}
        <div class="post" onclick="location.href='{% url "post-details" current_post.pk %}'">
            <div class="post-user">
                <img class="user-image" src="https://via.placeholder.com/40" alt="User Image">
                <div>
                    <p class="user-name">{{ current_post.user.username }}</p>
                    <p class="posted-hours">Posted on {{ current_post.date_time_of_publication }}</p>
                </div>
            </div>
            <h2 class="post-title">{{ current_post.post_title }}</h2>
            <p class="post-content">{{ current_post.post_content }}</p>
            <div class="imgBx" id="{{ current_post.id }}">
                {% if current_post.image %}
                    <img class="post-image" src="{{ current_post.image.url }}" alt="Image 1">
                {% endif %}
            </div>
            <div class="post-buttons">
                {% if request.user.is_authenticated %}
                    <a class="button" href="{% url 'like' current_post.id %}"><i class="icon fas fa-thumbs-up"></i>Like<span
                            class="count">{{ current_post.like_set.count }}</span></a>
                    <a class="button" href="{% url 'post-details' current_post.id %}?scroll_to_comment=true"><i
                            class="icon fas fa-comment"></i>Comment<span
                            class="count">{{ current_post.comment_set.count }}</span></a>
                {% else %}
                    <a class="button" href="{% url 'login' %}"><i class="icon fas fa-thumbs-up"></i>Like<span
                            class="count">{{ current_post.like_set.count }}</span></a>
                    <a class="button" href="{% url 'login' %}?scroll_to_comment=true"><i
                            class="icon fas fa-comment"></i>Comment<span
                            class="count">{{ current_post.comment_set.count }}</span></a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const categories = document.querySelectorAll('.category');

            categories.forEach(category => {
                category.addEventListener('click', () => {
                    category.classList.toggle('active');
                    updateArrowIcon(category);
                });
            });

            function updateArrowIcon(category) {
                const arrow = category.querySelector('.arrow');
                const subcategories = category.querySelector('.subcategories');

                if (category.classList.contains('active')) {
                    arrow.style.transform = 'rotate(90deg)';
                    subcategories.style.maxHeight = subcategories.scrollHeight + 'px';
                } else {
                    arrow.style.transform = 'rotate(0deg)';
                    subcategories.style.maxHeight = '0';
                }
            }
        });
    </script>
    </body>
    </html>

{% endblock %}

topictalk/topictalk/post/templates/post/post-details.html
{% extends 'base.html' %}

{% block content %}

    <!doctype html>
    <html lang="en" data-bs-theme="auto">
    <head>
        <script src="../assets/js/color-modes.js"></script>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Album example · Bootstrap v5.3</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/post-detials.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <link rel="stylesheet" href="/static/css/header.css">


    </head>
    <body>
    {% if request.user.id == current_post.user.id %}
        <div class="about-community">
            <div class="community-container">
                <h3>By clicking delete button, you can delete your own content!</h3>
                <a class="btn btn-outline-primary me-2" href="{% url 'delete-post' current_post.id %}">Delete</a>
            </div>
        </div>
    {% endif %}
    <div class="post">
        <div class="post-user">
            {% if current_profile.profile_picture %}
                <img class="user-image" src="{{ current_profile.profile_picture }}" alt="User Image">
            {% else %}
                <img class="user-image" src="/static/images/4038155-200.png"
                     alt="User Image">
            {% endif %}
            <div>
                <p class="user-name">{{ current_post.user.username }}</p>
                <p class="posted-hours">{{ current_post.date_time_of_publication }}</p>
            </div>
        </div>
        <h2 class="post-title">{{ current_post.post_title }}</h2>
        <p class="post-content">{{ current_post.post_content }}</p>
        <div class="imgBx">
            {% if current_post.image %}
                <img class="post-image" src="{{ current_post.image.url }}" alt="Image 1">
            {% endif %}
        </div>
        <div class="post-buttons">
            <a class="button" href="{% url 'like' current_post.id %}"><i class="icon fas fa-thumbs-up"></i>Like<span
                    class="count">{{ current_post.like_set.count }}</span></a>
            <a class="button" href="{% url 'post-details' current_post.id %}" id="scrollToCommentLink"><i
                    class="icon fas fa-comment"></i>Comment<span
                    class="count">{{ current_post.comment_set.count }}</span></a>
        </div>
    </div>


    <div class="container" id="commentContainer">
        <h1>Add Comment</h1>

        <!-- Comment form -->
        <form method="post" action="{% url 'comment' current_post.id %}">
            {% csrf_token %}
            {{ comment_form }}

            <button type="submit">Submit Comment</button>
        </form>
    </div>
    <div class="comments-container" id="{{ current_post.id }}">
        {% for comment in comments %}
            <div class="comment" id="{{ comment.id }}">
                <div class="comment-info">
                    <span>{{ request.user.username }}</span>
                    <span>{{ comment.date_time_of_publication }}</span>
                </div>
                <p>{{ comment.text }}</p>
                <div class="comment-actions">
                    <a class="action-btn like-btn" href="{% url 'like_comment' comment.id %}">Like</a>
                    <span
                            class="like-count"
                            id="likeCount_comment1">{{ comment.likecomment_set.count }} likes</span>
                    {% if request.user.id == comment.to_post.user_id %}
                        <a class="action-btn like-btn" id='delete-comment'
                       href="{% url 'delete-comment' comment.id current_post.id %}">Delete</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}

        <!-- Add more comments as needed -->
    </div>

    </body>
    </html>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const categories = document.querySelectorAll('.category');

            categories.forEach(category => {
                category.addEventListener('click', () => {
                    category.classList.toggle('active');
                    updateArrowIcon(category);
                });
            });

            function updateArrowIcon(category) {
                const arrow = category.querySelector('.arrow');
                const subcategories = category.querySelector('.subcategories');

                if (category.classList.contains('active')) {
                    arrow.style.transform = 'rotate(90deg)';
                    subcategories.style.maxHeight = subcategories.scrollHeight + 'px';
                } else {
                    arrow.style.transform = 'rotate(0deg)';
                    subcategories.style.maxHeight = '0';
                }
            }
        });
        // Check if the URL contains the query parameter 'scroll_to_comment'
        const urlParams = new URLSearchParams(window.location.search);
        const scrollToComment = urlParams.get('scroll_to_comment');

        if (scrollToComment === 'true') {
            // Get the target div element
            const commentContainer = document.getElementById('commentContainer');

            // Scroll to the target div smoothly
            commentContainer.scrollIntoView({behavior: 'smooth'});
        }

        document.getElementById('scrollToCommentLink').addEventListener('click', function (event) {
            event.preventDefault();

            // Get the target div element
            const commentContainer = document.getElementById('commentContainer');

            // Scroll to the target div smoothly
            commentContainer.scrollIntoView({behavior: 'smooth'});
        });


    </script>
{% endblock %}