topictalk/topictalk/common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from topictalk.common import views

urlpatterns = [
      path('', views.home, name='home'),
      path('like/<int:post_id>/', views.like_functionality, name='like'),
      path('like/comment/<int:comment_id>', views.like_functionality_about_comments, name='like_comment'),
      path('search/', views.search_view, name='search_view'),
  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

topictalk/topictalk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('topictalk.common.urls')),
    path('account/', include('topictalk.account.urls')),
    path('post/', include('topictalk.post.urls')),
]


topictalk/topictalk/common/models.py
from django.db import models

# Create your models here.

topictalk/topictalk/post/models.py
from django.db import models

from topictalk.account.models import TopicTalkUser
from topictalk.post.validators import validate_file_size

# Create your models here.
class Post(models.Model):
    Community = (
        ('League of Legends', 'League of Legends'),
        ('Minecraft', 'Minecraft'),
        ('NBA', 'NBA'),
        ('Premier League', 'Premier League'),
        ('Bitecoin', 'Bitecoin'),
        ('Litecoin', 'Litecoin')
    )
    choose_community = models.CharField(max_length=20, choices=Community)
    post_title = models.CharField(max_length=30)
    post_content = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='images', blank=True, null=True, validators=[validate_file_size])
    date_time_of_publication = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(TopicTalkUser, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.post_title

    class Meta:
        ordering = ['-date_time_of_publication']


class Comment(models.Model):
    text = models.TextField(max_length=300)
    date_time_of_publication = models.DateTimeField(auto_now_add=True)
    to_post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date_time_of_publication']


class Like(models.Model):
    to_post = models.ForeignKey(Post, on_delete=models.CASCADE)


class LikeComment(models.Model):
    to_comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

topictalk/topictalk/common/forms.py
from django import forms


class SearchForm(forms.Form):
    search_query = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": 'Search by community...'
            }
        ),
        label=''
    )
    section = forms.CharField(max_length=100, required=False)

topictalk/topictalk/common/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect

from topictalk.common.forms import SearchForm
from topictalk.post.models import Post, Like, Comment, LikeComment


# Create your views here.
def home(request):
    all_posts = Post.objects.all()

    context = {
        'all_posts': all_posts,
    }

    return render(request, template_name='common/home-page.html', context=context)


def search_view(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        if Post.objects.filter(choose_community__icontains=searched):
            return redirect(f'{searched.lower()}')
        else:
            return render(request, 'common/search.html', {'searched': searched})


def like_functionality(request, post_id):
    post = Post.objects.get(id=post_id)
    liked_object = Like.objects.filter(to_post_id=post_id).first()

    if liked_object:
        liked_object.delete()
    else:
        like = Like(to_post=post)
        like.save()

    return redirect(request.META['HTTP_REFERER'] + f'#{post_id}')


def like_functionality_about_comments(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    liked_comment = LikeComment.objects.filter(to_comment_id=comment_id).first()

    if liked_comment:
        liked_comment.delete()
    else:
        like = LikeComment(to_comment=comment)
        like.save()

    return redirect(request.META['HTTP_REFERER'] + f'#{comment_id}')



topictalk/topictalk/common/templates/common/home-page.html
{% extends 'base.html' %}

{% block content %}
    <!doctype html>
    <html lang="en" data-bs-theme="auto">
    <head>
        <script src="../assets/js/color-modes.js"></script>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Album example · Bootstrap v5.3</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <link rel="stylesheet" href="/static/css/home-page.css">
        <link href="/static/css/sign-in.css" rel="stylesheet">
        <link rel="stylesheet" href="/static/css/header.css">


    </head>
    <body>

    <div class="about-community">
        <div class="community-container">
            <h2>Create post</h2>
            <p>This is the best forum page!</p>
            {% if request.user.is_authenticated %}
                <a class="btn btn-outline-primary me-2" href="{% url 'post-create' %}">Create
                    post</a>
            {% else %}
                <a class="btn btn-outline-primary me-2" href="{% url 'login' %}">Create
                    post</a>
            {% endif %}
        </div>
    </div>

    {% for post in all_posts %}
        {% if request.user.is_authenticated %}
            <div class="post" onclick="location.href='{% url "post-details" post.pk %}'" id="{{ post.id }}">
                <div class="post-user">
                    {% if post.user.profile_picture %}
                        <img class="user-image" src="{{ post.user.profile_picture }}" alt="User Image">
                    {% else %}
                        <img class="user-image" src="/static/images/4038155-200.png"
                             alt="User Image">
                    {% endif %}
                    <div>
                        <p class="user-name">{{ post.user.username }}</p>
                        <p class="posted-hours">{{ post.date_time_of_publication }}</p>
                    </div>
                </div>
                <h2 class="post-title">{{ post.post_title }}</h2>
                <p class="post-content">{{ post.post_content }}</p>
                <div class="imgBx">
                    {% if post.image %}
                        <img class="post-image" src="{{ post.image.url }}" alt="Image 1">
                    {% endif %}
                </div>
                <div class="post-buttons">
                    {% if request.user.is_authenticated %}
                        <a class="button" href="{% url 'like' post.id %}"><i class="icon fas fa-thumbs-up"></i>Like<span
                                class="count">{{ post.like_set.count }}</span></a>
                        <a class="button" href="{% url 'post-details' post.id %}?scroll_to_comment=true"><i
                                class="icon fas fa-comment"></i>Comment<span
                                class="count">{{ post.comment_set.count }}</span></a>
                    {% else %}
                        <a class="button" href="{% url 'login' %}"><i class="icon fas fa-thumbs-up"></i>Like<span
                                class="count">{{ post.like_set.count }}</span></a>
                        <a class="button" href="{% url 'login' %}?scroll_to_comment=true"><i
                                class="icon fas fa-comment"></i>Comment<span
                                class="count">{{ post.comment_set.count }}</span></a>
                    {% endif %}
                </div>
            </div>
        {% else %}
            <div class="post" onclick="location.href='{% url 'login' %}'" id="{{ post.id }}">
                <div class="post-user">
                    {% if post.user.profile_picture %}
                        <img class="user-image" src="{{ post.user.profile_picture }}" alt="User Image">
                    {% else %}
                        <img class="user-image" src="/static/images/4038155-200.png"
                             alt="User Image">
                    {% endif %}
                    <div>
                        <p class="user-name">{{ post.user.username }}</p>
                        <p class="posted-hours">{{ post.date_time_of_publication }}</p>
                    </div>
                </div>
                <h2 class="post-title">{{ post.post_title }}</h2>
                <p class="post-content">{{ post.post_content }}</p>
                <div class="imgBx">
                    {% if post.image %}
                        <img class="post-image" src="{{ post.image.url }}" alt="Image 1">
                    {% endif %}
                </div>
                <div class="post-buttons">
                    {% if request.user.is_authenticated %}
                        <a class="button" href="{% url 'like' post.id %}"><i class="icon fas fa-thumbs-up"></i>Like<span
                                class="count">{{ post.like_set.count }}</span></a>
                        <a class="button" href="{% url 'post-details' post.id %}?scroll_to_comment=true"><i
                                class="icon fas fa-comment"></i>Comment<span
                                class="count">{{ post.comment_set.count }}</span></a>
                    {% else %}
                        <a class="button" href="{% url 'login' %}"><i class="icon fas fa-thumbs-up"></i>Like<span
                                class="count">{{ post.like_set.count }}</span></a>
                        <a class="button" href="{% url 'login' %}?scroll_to_comment=true"><i
                                class="icon fas fa-comment"></i>Comment<span
                                class="count">{{ post.comment_set.count }}</span></a>
                    {% endif %}
                </div>
            </div>
        {% endif %}

    {% endfor %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const categories = document.querySelectorAll('.category');

            categories.forEach(category => {
                category.addEventListener('click', () => {
                    category.classList.toggle('active');
                    updateArrowIcon(category);
                });
            });

            function updateArrowIcon(category) {
                const arrow = category.querySelector('.arrow');
                const subcategories = category.querySelector('.subcategories');

                if (category.classList.contains('active')) {
                    arrow.style.transform = 'rotate(90deg)';
                    subcategories.style.maxHeight = subcategories.scrollHeight + 'px';
                } else {
                    arrow.style.transform = 'rotate(0deg)';
                    subcategories.style.maxHeight = '0';
                }
            }
        });


    </script>

{% endblock %}

topictalk/topictalk/common/templates/common/search.html
{% extends 'base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <link rel="stylesheet" href="/static/css/header.css">
        <link rel="stylesheet" href="/static/css/search.css">
    </head>
    <body>
    <section>
        <div class="no-results-container">
            <img class="no-results-image" src="/static/images/cute-line-drawing-of-a-sad-bear-KXHDE6.jpg" alt="No Results Image">
            <p class="no-result-text">Hm... we couldn’t find any results for {{ searched }}</p>
        </div>
    </section>
    </body>
    </html>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const categories = document.querySelectorAll('.category');

            categories.forEach(category => {
                category.addEventListener('click', () => {
                    category.classList.toggle('active');
                    updateArrowIcon(category);
                });
            });

            function updateArrowIcon(category) {
                const arrow = category.querySelector('.arrow');
                const subcategories = category.querySelector('.subcategories');

                if (category.classList.contains('active')) {
                    arrow.style.transform = 'rotate(90deg)';
                    subcategories.style.maxHeight = subcategories.scrollHeight + 'px';
                } else {
                    arrow.style.transform = 'rotate(0deg)';
                    subcategories.style.maxHeight = '0';
                }
            }
        });
    </script>
{% endblock %}